[alias]
b = ["build", "--all-features"]
t = ["test", "--all-features", "--all-targets"]
td = ["test", "--all-features", "--doc"]
c = ["clippy", "--all-features", "--all-targets"]
r = ["run", "--all-features"]
